#  ____    ___                                ____                  ___         __     
# /\  _`\ /\_ \                            __/\  _`\              /'___`\     /'__`\   
# \ \ \L\_\//\ \      __      ____    ____/\_\ \ \L\_\__  __     /\_\ /\ \   /\ \/\ \  
#  \ \ \L_L \ \ \   /'__`\   /',__\  /',__\/\ \ \  _\/\ \/\ \    \/_/// /__  \ \ \ \ \ 
#   \ \ \/, \\_\ \_/\ \L\.\_/\__, `\/\__, `\ \ \ \ \/\ \ \_\ \      // /_\ \__\ \ \_\ \
#    \ \____//\____\ \__/.\_\/\____/\/\____/\ \_\ \_\ \/`____ \    /\______/\_\\ \____/
#     \/___/ \/____/\/__/\/_/\/___/  \/___/  \/_/\/_/  `/___/> \   \/_____/\/_/ \/___/ 
#                                                         /\___/                       
#                                                         \/__/                     


# GlassiFy 2.0.2511 - https://glassify.saviru.me
# ===========================================================
# An open-source and a lightweight Web Component for creating liquid glass effects with dynamic displacement.
# ================================================


# Â© 2025 Saviru Kashmira Atapattu. MIT License.
# Website: https://saviru.me
# GitHub: https://github.com/saviru


name: Archive Release Binaries & Info

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  archive-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Define Version
        id: vars
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger detected. Fetching latest release tag..."
            VERSION=$(gh release view --json tagName --jq .tagName)
          else
            VERSION="${{ github.event.release.tag_name }}"
          fi
          
          echo "Processing Version: $VERSION"
          
          TARGET_DIR="cdn/${VERSION}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV

      - name: Create Version Directory
        run: mkdir -p ${{ env.TARGET_DIR }}

      - name: Download Release Binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ env.VERSION }} \
            --dir ${{ env.TARGET_DIR }} \
            --pattern "*.js" \
            --skip-existing

      - name: Add Latest Release Binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ env.VERSION }} \
            --dir "cdn" \
            --pattern "*.js" \
            --clobber

      - name: Generate JSON Info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          JSON_FILE="release_info.json"
          
          gh release view ${{ env.VERSION }} \
            --json tagName,publishedAt,url,body \
            --jq '{version: .tagName, date: .publishedAt, url: .url, description: .body}' > $JSON_FILE
            
            
          cat $JSON_FILE

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add cdn/*
          git add release_info.json
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Release Version ${{ env.VERSION }}" \
              -m "Co-authored-by: Saviru <savirukashmira@gmail.com>"
            git pull origin main --rebase
            git push origin main
          fi